# .github/workflows/deploy-api.yml
name: Deploy Backend to Railway

on:
  push:
    paths:
      - 'apps/api/**'
      - 'app/api/prisma/**'
      - 'pnpm-lock.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Build API
        run: pnpm --filter api... build

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          command: up --service <your-service-id>
